server:
  port: 8000
spring:
  application:
    name: ad-eureka
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka


#---
#spring:
#  application:
#    name: ad-eureka
#  profiles: server1
#server:
#  port: 8000
#eureka:
#  instance:
#    hostname:  server1
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/
#
#
#---
#spring:
#  application:
#    name: ad-eureka
#  profiles: server2
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname:  server1
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server2:8000/eureka/,http://server3:8002/eureka/
#
#
#---
#spring:
#  application:
#    name: ad-eureka
#  profiles: server3
#server:
#  port: 8003
#eureka:
#  instance:
#    hostname:  server1
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server2:8001/eureka/,http://server3:8000/eureka/